export const INSUREDS = [
    {internalId: "A1B2", name: "Riley HealthCare LLC"},
    {internalId: "C3D4", name: "Quail Creek RE LLC"},
    {internalId: "E5F6", name: "William James Group LLC"},
    {internalId: "G7H8", name: "Northstar Logistics Inc."},
    {internalId: "I9J0", name: "Evergreen Farms Ltd."},
    {internalId: "K1L2", name: "Beacon Financial Services Corp"},
    {internalId: "M3N4", name: "Hudson Valley Medical Partners"},
    {internalId: "O5P6", name: "Sierra Manufacturing Co."},
    {internalId: "Q7R8", name: "Lakeside Property Holdings, LLC"},
    {internalId: "S9T0", name: "Atlas Retail Group, Inc."},
    {internalId: "U1V2", name: "Pioneer Energy Solutions"},
    {internalId: "W3X4", name: "Blue Ridge Hospitality Partners"},
    {internalId: "Y5Z6", name: "Copper Mountain Mining Corp."},
    {internalId: "B7C8", name: "Silverline Software Ltd."},
    {internalId: "D9E0", name: "Harbor Point Marine Services"},
    {internalId: "F1G2", name: "Metro Transit Authority"},
    {internalId: "H3I4", name: "Golden Gate Ventures LLC"},
    {internalId: "J5K6", name: "Cypress Pharmaceuticals, Inc."},
    {internalId: "L7M8", name: "Redwood Timber Holdings"},
    {internalId: "N9O0", name: "Summit Peak Outdoor Gear"},
    {internalId: "P1Q2", name: "Capital Square Investments"},
    {internalId: "R3S4", name: "Ironclad Security Solutions"},
    {internalId: "T5U6", name: "Frontier Airlines Group"},
    {internalId: "V7W8", name: "Majestic Resorts & Spas Ltd."},
    {internalId: "X9Y0", name: "Orchard Valley Foods"},
    {internalId: "Z1A2", name: "Starlight Entertainment Corp"},
    {internalId: "B3D4", name: "Cascade Water Works"},
    {internalId: "F5H6", name: "Urban Grid Construction"},
    {internalId: "J7L8", name: "Vertex Capital Management"},
]
